// Executes the production JavaScript in an isolated, offline Chrome context.
// All provider URLs are fulfilled with local fixtures. No casino is contacted.
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const src=fs.readFileSync(process.env.BACCARAT_SOURCE||path.join(__dirname,'../src/main.cpp'),'utf8');
const section=(a,b)=>src.slice(src.indexOf(a),src.indexOf(b,src.indexOf(a)));
const production=section('const toRootViewportPoint=','const mainTarget=')+
  section('const controlPoint=','const stablePairSignature=')+
  (src.includes('const requestChipSelectorOpen=')?section('const requestChipSelectorOpen=','const storePairClickCoords='):'');
const values=['0,2','1','2','5','25','100','250','1K'];
const chip=(v,i)=>`<button class="zz" data-denomination="${v}" onclick="selectChip('${v}')"><svg viewBox="0 0 40 40"><text x="20" y="25" text-anchor="middle">${v}</text></svg></button>`;
const style=`<style>*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;font:16px Arial}button{padding:0;border:0;cursor:pointer;color:white;background:#bd6512;border-radius:50%}svg{width:100%;height:100%;pointer-events:none}text{fill:white}.table{position:absolute;top:15px;left:10px;width:210px;height:160px;background:#ccc}.vertical{position:absolute;right:12px;top:100px;width:42px;height:430px;display:flex;flex-direction:column;gap:12px}.vertical button{width:42px;height:42px;flex:none}.component{position:absolute;bottom:0;left:0;width:100%;height:205px;pointer-events:none}.stack{position:absolute;bottom:10px;left:calc(50% - 22px);width:44px;height:44px;pointer-events:auto;z-index:4}.decor{position:absolute;bottom:15px;width:28px;height:28px;pointer-events:none}.a{left:calc(50% - 35px)}.b{left:calc(50% + 7px)}.options{opacity:0;pointer-events:none}.options button{position:absolute;width:33px;height:33px;pointer-events:none}.component.open .options{opacity:1}.component.open .options button{pointer-events:auto}.component.open .stack{width:88px;height:88px;left:calc(50% - 44px);bottom:18px}.component.open .decor{display:none}</style>`;
function mainHTML(){return style+`<div id="table" class="table">Baccarat 1 ID: 123</div><div class="vertical">${[...values].reverse().map(chip).join('')}</div><script>function selectChip(v){document.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.denomination===v?'true':'false'))}</script>`}
function multiHTML(){const coords=[[13,100],[24,57],[51,23],[88,8],[130,8],[168,26],[196,60],[205,103]];
 return style+`<div id="table" class="table">Baccarat 9 ID: 123 <span>0,2 €</span></div><div class="component" id="component"><div class="options">${values.map((v,i)=>chip(v,i).replace('class="zz"',`class="zz" style="left:${coords[i][0]}px;top:${coords[i][1]}px"`)).join('')}</div><span class="decor a">0,2</span><span class="decor b">2</span><button class="stack" onclick="this.parentElement.classList.toggle('open')"><svg viewBox="0 0 40 40"><text x="20" y="25" text-anchor="middle">1</text></svg></button></div><script>function selectChip(v){document.querySelector('.stack text').textContent=v;document.querySelector('.component').classList.remove('open')}</script>`;
}
const base='https://client.pragmaticplaylive.net';
const results=[];
async function run(name,fn){try{await fn();results.push({name,ok:true});console.log('PASS '+name)}catch(e){results.push({name,ok:false,error:String(e)});console.error('FAIL '+name+' '+e.stack)}}
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||'C:/Program Files/Google/Chrome/Application/chrome.exe'});
 try{
  const context=await browser.newContext({viewport:{width:1280,height:760},serviceWorkers:'block'});
  await context.route('**/*',route=>{const u=route.request().url();let html=u.endsWith('/launcher/')?`<style>body{margin:0}iframe{position:absolute;top:30px;border:0;height:690px}#main{left:20px;width:940px}#multi{left:970px;width:255px}</style><iframe id="main" src="${base}/desktop/baccarat/"></iframe><iframe id="multi" src="${base}/desktop/multibaccarat/"></iframe>`:u.endsWith('/multibaccarat/')?multiHTML():mainHTML();return route.fulfill({contentType:'text/html',body:html})});
  const page=await context.newPage();await page.goto(base+'/desktop/launcher/');
  async function install(mode){await page.evaluate(({production,mode})=>{
    const frame=document.getElementById(mode).contentWindow;
    const setup=`const ROOT_WINDOW=globalThis,ROOT_DOCUMENT=globalThis.document,window=ROOT_DOCUMENT.getElementById('${mode}').contentWindow,document=window.document,NodeFilter=window.NodeFilter,isMulti=${mode==='multi'};const SOURCE_GAME='123',TARGET_NAME='${mode==='multi'?'Baccarat 9':'Baccarat 1'}';const norm=s=>String(s||'').replace(/\\s+/g,' ').trim(),lower=s=>norm(s).toLowerCase(),visible=el=>!!el;const tableTextMatches=t=>norm(t).startsWith(TARGET_NAME);const AUTO_BET_REQUEST=true,RUN_TOKEN='run',TARGET_ID='table',REQUEST_TOKEN='7',context='test',href=window.location.href;const operation={finished:false};`;
    (0,eval)(setup+production+`;globalThis.api={chipTarget,chipRackRoot,chipDocuments,controlPoint,chipActiveEvidence,chipSourceByHit,table:document.getElementById('table'),operation,${production.includes('const multiplayChipSelector=')?'multiplayChipSelector,selectedMultiplayChip,requestChipSelectorOpen,':''}diag:()=>lastChipSearchDiag};`);
  },{production,mode})}
  await run('vertical main rack is recognized at 42 x 430',async()=>{await install('main');const r=await page.evaluate(()=>{const r=api.chipRackRoot(api.table)?.getBoundingClientRect();return r&&[r.width,r.height]});assert.deepEqual(r,[42,430])});
  await run('main 0.20 and 1K resolve to their own buttons',async()=>{for(const [cents,label]of[[20,'0,2'],[100000,'1K']]){const r=await page.evaluate(c=>{const target=api.chipTarget(c,api.table),p=api.controlPoint(target);return {text:target?.textContent,point:p}},cents);assert.equal(r.text,label);assert(r.point.x>880&&r.point.x<960)}});
  await run('closed MULTIPLAY does not use the main-table rack',async()=>{await install('multi');assert.equal(await page.evaluate(()=>api.chipTarget(20,api.table)===null),true)});
  await run('opener resolves the center chip, not table minimum or decorative chips',async()=>{const p=await page.evaluate(()=>{const s=api.multiplayChipSelector(api.table);return {denom:s?.denom,open:s?.open,point:s&&api.controlPoint(s.el)}});assert.equal(p.denom,'1');assert.equal(p.open,false);assert(p.point.x>1080&&p.point.x<1120);assert(p.point.y>650)});
  await run('open request is emitted once per phase without synthetic selection',async()=>{const msgs=[];const listener=msg=>{if(msg.text().startsWith('__BAC_CHIP_SELECTOR_OPEN_COORDS__'))msgs.push(JSON.parse(msg.text().split('__BAC_CHIP_SELECTOR_OPEN_COORDS__')[1]))};page.on('console',listener);assert.deepEqual(await page.evaluate(()=>[api.requestChipSelectorOpen(api.table,'pair'),api.requestChipSelectorOpen(api.table,'pair')]),[true,false]);page.off('console',listener);assert.equal(msgs.length,1);await page.mouse.click(msgs[0].x,msgs[0].y)});
  await run('expanded radial menu resolves 0.20 within MULTIPLAY',async()=>{const r=await page.evaluate(()=>{const target=api.chipTarget(20,api.table);return {text:target?.textContent,point:api.controlPoint(target),diag:api.diag()}});assert.equal(r.text,'0,2',JSON.stringify(r.diag));assert(r.point.x>970);await page.mouse.click(r.point.x,r.point.y)});
  await run('collapsed display confirms selected 0.20 and rejects 1',async()=>{const r=await page.evaluate(()=>({chosen:!!api.selectedMultiplayChip(20,api.table),wrong:!!api.selectedMultiplayChip(100,api.table),evidence:api.chipActiveEvidence(api.selectedMultiplayChip(20,api.table))}));assert.equal(r.chosen,true);assert.equal(r.wrong,false);assert.equal(r.evidence.active,true)});
  await run('a later phase can reopen and remeasure the menu',async()=>{assert.equal(await page.evaluate(()=>api.requestChipSelectorOpen(api.table,'main')),true)});
  await run('bare bottom number without chip group is rejected',async()=>{await page.frames().find(f=>f.url().endsWith('/multibaccarat/')).evaluate(()=>{document.querySelector('.options').remove();document.querySelectorAll('.decor').forEach(e=>e.remove())});assert.equal(await page.evaluate(()=>api.multiplayChipSelector(api.table)),null)});
  await run('coordinates preserve source label center when hit target is larger',async()=>{await install('main');const r=await page.evaluate(()=>{const d=api.table.ownerDocument;const b=d.createElement('button');b.style='position:absolute;left:100px;top:600px;width:180px;height:60px';b.innerHTML='<span style="position:absolute;left:10px;top:15px;width:30px;height:30px;pointer-events:none">1</span>';d.body.append(b);api.chipSourceByHit.set(b,b.firstChild);return api.controlPoint(b)});assert.equal(r.x,145);assert.equal(r.y,660)});
  await context.close();
 }finally{await browser.close()}
 const report=process.env.TEST_REPORT;if(report)fs.writeFileSync(report,JSON.stringify(results,null,2));
 if(results.some(r=>!r.ok))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
