// Offline reproduction of structural observations from cpp_capture_20260916_161904.
// No player/account data, network requests or real wagers are used.
const fs=require('node:fs'),path=require('node:path');
const target=path.resolve(__dirname,'../.validation/captured-chip-ui');fs.mkdirSync(target,{recursive:true});
const values=['0.2','1','2','5','25','100','250','1000'];
function label(v){return v==='1000'?'1K':v.replace('.',',')}
function svg(v){const text=label(v).split('').map(c=>`<tspan>${c}</tspan>`).join('');return `<span data-testid="chip"><svg viewBox="0 0 40 40"><g data-testid="chip-inner-text"><text x="8" y="25">${text}</text><text x="8" y="24">${text}</text></g></svg></span>`}
function option(v){return `<div data-testid="chip-stack-value-${v}" class="option ${Number(v)>=250?'unavailable':''}" onclick="selectChip('${v}')">${svg(v)}</div>`}
const style=`<style>*{box-sizing:border-box}body{margin:0;font:16px Arial}button{border:0;padding:0;background:none;cursor:pointer}svg{width:100%;height:100%;pointer-events:none}text{fill:white;pointer-events:none}[data-testid="chip"]{display:flex;position:relative;width:40px;height:40px;border-radius:50%;background:#e39000;cursor:pointer}[data-testid="chip-inner-text"]{pointer-events:none}.option{position:relative;display:flex;align-items:center;justify-content:center;cursor:pointer}.unavailable,.unavailable *{pointer-events:none!important}.unavailable{opacity:.4}.table{position:absolute;left:12px;top:570px;width:220px;height:120px}.table small{position:absolute;bottom:12px}.selected{transform:translateY(-5.6px)}</style>`;
const main=style+`<div class="table" id="table">Baccarat 1 ID: 123 <small>0,2 €</small></div><div data-testid="layout-controls" style="position:absolute;right:8px;top:15px;width:40px;height:642px"><div data-testid="chip-stack-bar" style="position:absolute;right:-6px;top:113px;width:52px;height:416px">${[...values].reverse().map(v=>`<div data-testid="show-context-message" style="width:52px;height:52px">${option(v)}</div>`).join('')}</div></div><style>.option{width:52px;height:52px}</style><script>function selectChip(v){document.querySelectorAll('.option').forEach(e=>e.classList.toggle('selected',e.dataset.testid==='chip-stack-value-'+v))}</script>`;
const coords=[[12,612.41],[22,565],[55,535],[99,518],[141,518],[180,535],[207,565],[209,612.41]];
const multi=style+`<div class="table" id="table">Baccarat 9 ID: 123 <small>0,2 €</small></div><div data-testid="layout-controls" style="position:absolute;bottom:0;left:8px;width:237px;height:49.59px"><div data-testid="chip-stack-revolver" id="component"><div data-testid="revolver-chip-stack-drawer" id="drawer">${values.map((v,i)=>option(v).replace('class="option',`style="--ox:${coords[i][0]}px;--oy:${coords[i][1]}px" class="option`)).join('')}</div><button data-testid="chip-stack-revolver-button" onclick="document.getElementById('component').classList.toggle('open')"><span class="decor left">${svg('0.2')}</span><span class="current">${svg('1')}</span><span class="decor right">${svg('2')}</span></button></div></div><style>
[data-testid="chip-stack-revolver"]{position:fixed;left:97.5px;top:648.2px;width:66px;height:40px}
[data-testid="chip-stack-revolver-button"]{position:relative;display:flex;justify-content:center;width:66px;height:40px;z-index:4}
.decor{position:absolute;top:4px;opacity:.75}.decor [data-testid="chip"]{width:32px;height:32px}.left{left:0}.right{right:0}.current{z-index:2;position:relative}
#drawer{position:fixed;left:-11px;top:526.7px;width:283px;height:283px;pointer-events:none}
#drawer .option{position:fixed;left:130.5px;top:626.61px;width:40px;height:40px;pointer-events:none}
#drawer [data-testid="chip"]{width:32px;height:32px}
.open[data-testid="chip-stack-revolver"]{top:613.2px}.open #drawer{top:491.7px;pointer-events:auto}.open #drawer .option{left:var(--ox);top:var(--oy);pointer-events:auto}
.open .current{transform:scale(2.15)}.open .decor{opacity:0}
</style><script>function selectChip(v){document.querySelectorAll('.current text').forEach(el=>el.innerHTML=(v==='1000'?'1K':v.replace('.',',')).split('').map(c=>'<tspan>'+c+'</tspan>').join(''));document.getElementById('component').classList.remove('open')}</script>`;
for(const [name,html] of Object.entries({baccarat:main,multibaccarat:multi})){
 const dir=path.join(target,'desktop',name);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html);
}
const src=fs.readFileSync(process.argv[2]||path.join(__dirname,'../src/main.cpp'),'utf8');
const section=(a,b)=>src.slice(src.indexOf(a),src.indexOf(b,src.indexOf(a)));
const production=section('const toRootViewportPoint=','const mainTarget=')+section('const controlPoint=','const stablePairSignature=')+section('const requestChipSelectorOpen=','const storePairClickCoords=');
const setup=mode=>`const ROOT_WINDOW=globalThis,ROOT_DOCUMENT=globalThis.document,window=ROOT_DOCUMENT.getElementById('${mode}').contentWindow,document=window.document,NodeFilter=window.NodeFilter,isMulti=${mode==='multi'};const SOURCE_GAME='123',TARGET_NAME='${mode==='multi'?'Baccarat 9':'Baccarat 1'}';const norm=s=>String(s||'').replace(/\\s+/g,' ').trim(),lower=s=>norm(s).toLowerCase(),visible=el=>!!el;const tableTextMatches=t=>norm(t).startsWith(TARGET_NAME);const AUTO_BET_REQUEST=true,RUN_TOKEN='run',TARGET_ID='table',REQUEST_TOKEN='7',context='test',href=window.location.href;const operation={finished:false};`;
const code=`const production=${JSON.stringify(production)},setups=${JSON.stringify({main:setup('main'),multi:setup('multi')})};
function install(mode){(0,eval)(setups[mode]+production+';globalThis.api={chipElementDenoms,chipTarget,chipRackRoot,controlPoint,chipSourceByHit,chipActiveEvidence,multiplayChipSelector,selectedMultiplayChip,requestChipSelectorOpen,table:document.getElementById("table"),diag:()=>lastChipSearchDiag};')}
function assert(ok,message){if(!ok)throw Error(message||'Assertion failed')}
const results=[];function test(name,fn){try{fn();results.push({name,ok:true})}catch(e){results.push({name,ok:false,error:String(e)})}}
function clickPoint(p){assert(p,'no point');const frame=document.elementFromPoint(p.x,p.y);assert(frame?.tagName==='IFRAME','wrong frame');const r=frame.getBoundingClientRect(),hit=frame.contentDocument.elementFromPoint(p.x-r.left,p.y-r.top);assert(hit,'no hit');hit.click()}
function hasValue(el,value){return !!el&&el.closest('[data-testid="chip-stack-value-'+value+'"]')!==null}
function run(){
test('Split SVG and shadow copies preserve all eight denominations',()=>{install('main');const d=api.table.ownerDocument;for(const v of ${JSON.stringify(values)}){const found=[...api.chipElementDenoms(d.querySelector('[data-testid="chip-stack-value-'+v+'"]'))];assert(found.length===1&&found[0]===v,v+' parsed as '+found)}});
test('Main 0.20 selects exact control despite duplicated 0,20,2 text',()=>{const el=api.chipTarget(20,api.table);assert(hasValue(el,'0.2'),JSON.stringify(api.diag()));const p=api.controlPoint(el);assert(p?.x>960&&p.x<980&&p.y>520&&p.y<560,JSON.stringify(p))});
test('Main all affordable denominations resolve to own controls',()=>{for(const c of [100,200,500,2500,10000])assert(hasValue(api.chipTarget(c,api.table),String(c/100)),'wrong '+c)});
test('Disabled 250 and 1K do not select tooltip ancestor or smaller chip',()=>{for(const c of [25000,100000])assert(api.chipTarget(c,api.table)===null,'disabled '+c+' accepted')});
test('Enabled 1K remains 1000 instead of reading its first digit',()=>{const d=api.table.ownerDocument;d.querySelector('[data-testid="chip-stack-value-1000"]').classList.remove('unavailable');assert(hasValue(api.chipTarget(100000,api.table),'1000'))});
test('Collapsed drawer is not treated as open although labels have opacity 1',()=>{install('multi');const s=api.multiplayChipSelector(api.table);assert(s&&s.denom==='1'&&s.open===false,JSON.stringify(s&&{denom:s.denom,open:s.open}));assert(api.chipTarget(20,api.table)===null,'hidden option accepted')});
test('Captured revolver button supplies correct footer coordinates',()=>{const s=api.multiplayChipSelector(api.table),p=s&&api.controlPoint(s.el);assert(p&&Math.abs(p.x-1129.5)<1&&Math.abs(p.y-698.2)<1,JSON.stringify(p))});
test('Native open request is emitted once and opens fixture',()=>{const logs=[],old=console.log;console.log=x=>logs.push(x);try{assert(api.requestChipSelectorOpen(api.table,'pair'));assert(!api.requestChipSelectorOpen(api.table,'pair'))}finally{console.log=old}assert(logs.length===1);clickPoint(JSON.parse(logs[0].split('__BAC_CHIP_SELECTOR_OPEN_COORDS__')[1]))});
test('Expanded drawer is detected outside narrow frame bounds',()=>{const s=api.multiplayChipSelector(api.table);assert(s?.open,'not open')});
test('MULTIPLAY 0.20 chooses option rather than decorative neighbour',()=>{const el=api.chipTarget(20,api.table);assert(hasValue(el,'0.2'),JSON.stringify(api.diag()));const p=api.controlPoint(el);assert(Math.abs(p.x-1031)<1&&Math.abs(p.y-662.41)<1,JSON.stringify(p));clickPoint(p)});
test('Selected 0.20 is confirmed from split duplicated center label',()=>{assert(api.selectedMultiplayChip(20,api.table),'0.20 unconfirmed');assert(!api.selectedMultiplayChip(200,api.table),'0.20 confused with 2');assert(!api.selectedMultiplayChip(100,api.table),'0.20 confused with 1')});
test('Disabled MULTIPLAY denomination stays unavailable when open',()=>{api.table.ownerDocument.getElementById('component').classList.add('open');assert(api.chipTarget(100000,api.table)===null)});
test('Covered chip fails instead of returning unrelated overlay',()=>{const d=api.table.ownerDocument,b=d.createElement('div');b.style='position:fixed;left:0;top:0;width:100%;height:100%;z-index:99';d.body.append(b);assert(api.chipTarget(20,api.table)===null);b.remove()});
test('Fallback also reads SVG logical labels without provider test IDs',()=>{install('main');const d=api.table.ownerDocument;d.querySelectorAll('[data-testid]').forEach(e=>e.removeAttribute('data-testid'));for(const c of [20,2500,10000,100000]){const el=api.chipTarget(c,api.table);assert(el,'missing '+c);const found=[...api.chipElementDenoms(el)];assert(found.length===1&&found[0]===String(c/100),'wrong '+c+' => '+found)}});
document.getElementById('results').textContent=JSON.stringify(results,null,2);document.title=results.filter(x=>x.ok).length+'/'+results.length+' captured chip tests';window.testResults=results;
}window.addEventListener('load',run);`;
const html=`<!doctype html><meta charset="utf-8"><title>Captured chip tests</title><style>body{margin:0}iframe{position:absolute;top:30px;border:0;height:693px}#main{left:20px;width:979px}#multi{left:999px;width:253px}#results{position:absolute;top:730px;white-space:pre-wrap}</style><iframe id="main" src="desktop/baccarat/index.html"></iframe><iframe id="multi" src="desktop/multibaccarat/index.html"></iframe><pre id="results">Running local tests</pre><script>${code.replace(/<\/script/gi,'<\\/script')}</script>`;
fs.writeFileSync(path.join(target,process.argv[3]||'index.html'),html);
console.log('Captured structure fixture generated at '+target);
